apiVersion: apps/v1
kind: Deployment
metadata:
  name: folding-at-home
  labels:
    app.kubernetes.io/name: folding-at-home
    app.kubernetes.io/version: "latest"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: folding-at-home
      app.kubernetes.io/version: "latest"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: folding-at-home
        app.kubernetes.io/version: "latest"
    spec:
      volumes:
        - name: data-volume
          emptyDir: {}
      containers:
        - name: folding-at-home
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "wind0r/folding-at-home:latest"
          imagePullPolicy: Always
          env:
            - name: USER
              value: "PapaVietmeier"
            - name: TEAM
              value: "1064672"
            - name: PASSKEY
              valueFrom:
                secretKeyRef:
                  name: folding-at-home
                  key: passkey
                  optional: true
            - name: POWER
              value: "full"
          volumeMounts:
            - mountPath: /home/folding
              name: data-volume
          ports:
            - name: http
              containerPort: 7396
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /favicon.ico
              port: 7396
          resources:
            limits:
              cpu: "1"
              memory: 500Mi
            requests:
              cpu: "0.5"
              memory: 200Mi
# Working now
# Need to use full name for app selector
---
apiVersion: v1
kind: Service
metadata:
  name: folding
spec:
  type: LoadBalancer
  ports:
  - port: 7396
  selector:
    app.kubernetes.io/name: folding-at-home